name: example
version: 1.0.0
homepage: https://github.com/gtgalone/alert_dialog
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  alert_dialog:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.15.7

dependency_overrides:
  alert_dialog:
    path: ../
