name: alert_dialog
description: Alert Dialog Widget JS-LIKE for Flutter. Use alert dialog easy and simple for your flutter app.
version: 0.0.2
homepage: https://github.com/gtgalone/alert_dialog

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
